### ISSUE TITLE
Setting skip_paths to all the paths hit, stops custom metrics from working

### ISSUE THREAD

**Issue by aodj** [kozhushman/prometheusrock#2]
If you configure `skip_paths` to be a list of all the paths you visit, ie: `["/metrics", "/favicon.ico"]` then the `custom_metrics` functions are never invoked.

I think this is because the logic for the [`custom_metrics`](https://github.com/kozhushman/prometheusrock/blob/main/prometheusrock/middleware.py#L113-L118) is under the `if request.url.path not in self.skip_paths:` logic.

I encountered this when using this method to disable the `REQUEST_TIME` metric.

**Comment by kozhushman** [comment]
Can you tell me what result are you trying to get? If you add all the paths to `skip_paths`, obviously `custom_metrics` is never invoked, because all paths are skipped.
If you want to disable one of the default metrics, I think I can add an optional parameter for that

**Comment by aodj** [comment]
Initially I was simply trying to disable the `request_processing_time` metrics, which I did by setting `skip_paths=["/metrics", "/favicon.ico"]`.

I determined I was never going to use metrics about 404 request processing time to a non-existent favicon.ico, which the default configuration sets:

```
# HELP requests_total Total HTTP requests
# TYPE requests_total counter
requests_total{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",method="GET",path="/favicon.ico",status_code="404"} 1.0
# HELP requests_created Total HTTP requests
# TYPE requests_created gauge
requests_created{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",method="GET",path="/favicon.ico",status_code="404"} 1.604400990556766e+09
# HELP request_processing_time HTTP request processing time in seconds
# TYPE request_processing_time histogram
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.005",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.01",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.025",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.05",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.075",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.1",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.25",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.5",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="0.75",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="1.0",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="2.5",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="5.0",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="7.5",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="10.0",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_bucket{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",le="+Inf",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_count{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",method="GET",path="/favicon.ico",status_code="404"} 1.0
request_processing_time_sum{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",method="GET",path="/favicon.ico",status_code="404"} 0.00047087669372558594
# HELP request_processing_time_created HTTP request processing time in seconds
# TYPE request_processing_time_created gauge
request_processing_time_created{app_name="myapp",headers="{'host': '127.0.0.1:8080', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0'}",method="GET",path="/favicon.ico",status_code="404"} 1.604400990556919e+09
```

The application I'm building has no other endpoints, so it will only ever receive requests to this path (and maybe the default health check path in FastAPI). 

What came as a surprise was that I had added some custom metrics, returning some values from a db query and they were not returned once I added `"/favicon.ico"` to the `skip_paths` list.

My understanding was that by calling the `AddMetric` function, _any_ metric could be added, for exposure via Prometheus; if the `skip_paths` list is set to cover all the endpoint your application contains, custom metrics are never exposed.

**Comment by kozhushman** [comment]
> The application I'm building has no other endpoints, so it will only ever receive requests to this path 

By "this path" you meaning `/favicon.ico`?

When you want your custom metric to activates? After request to  `/favicon.ico`?

**Comment by aodj** [comment]
> By "this path" you meaning /favicon.ico?

No, just `/metrics`.

My apologies I'm not expressing myself clearly; the FastAPI app I'm writing is for executing basic database queries to generate Prometheus metrics. It has no endpoints beyond the `/metrics` endpoint implemented by your prometheusrocks middleware. 

Since there are no other endpoints on the application, and I have no need for the `request_processing_time` metrics I was attempting to disable them, however the reliance upon another endpoint existing as a trigger mechanism for the custom metrics means that when I attempt to disable the `request_processing_time` metric by setting the `skip_paths` variable, I end up with no metrics. 

As for `/favicon.ico` I have no intent to visit that endpoint specifically; it's only happening because I'm navigating to `http://127.0.0.1:8080/metrics` in Firefox, and the browser attempts to load favicons by default.

**Comment by kozhushman** [comment]
Ah, get it! Thanks for clarification!

If I'll made following changes, will it be helpful in your case?

- Opportunity to disable default skip of `/metric` path
- Opportunity to disable default metrics

**Comment by aodj** [comment]
I think in my use-case, the second is most helpful.

Is the first option not possible currently by setting `skip_paths = []`? 

My concern with it for applications with many endpoints is that it generates a large quantity of multi-label data which if you have a large application being accessed by many browsers would end up with a lot of high cardinal data with the default configuration.

**Comment by kozhushman** [comment]
> Is the first option not possible currently by setting skip_paths = []?

Unfortunetely, no. Bad architecture solution, as how I understand at the moment.

Hm, your concerns are pretty reasonable, I must think about that.

New version with this features will be as soon as possible, I'll close the issue when it be ready

**Comment by kozhushman** [comment]
Updated docs and code, if there will be further problems, let me know!
