### ISSUE TITLE
Question: How to access the Request object in my custom metric function?

### ISSUE THREAD

**Issue by t111** [kozhushman/prometheusrock#3]
Hi, firstly thank you for offering this great tool! It's so nice and clean!

I'd like to collect data from the request object, is there a way to access it?.
```python
async def custom_metric(middleware_proxy: Metric):
    res = do_something_with_request_obj() # how to get the request object?
    middleware_proxy.metric.labels(**res)
```

**Comment by kozhushman** [comment]
Hi! Thanks, I appreciate that :)

Currently no, you cannot, but as it seems it may be needed - so I implement it as soon as possible. About 1 or 2 days I hope

**Comment by kozhushman** [comment]
I uploaded new version, where you can access the request object from middleware_proxy object (see in README) - in short - middleware_proxy.request

**Comment by t111** [comment]
It looks great!
Thank you so much!
