### ISSUE TITLE
Managing metrics for multiple workers/processes?

### ISSUE THREAD

**Issue by Aldo111** [kozhushman/prometheusrock#4]
Hey great library but just one question - how does this manage metrics coming from multiple api processes? for eg. I run uvicorn with 8 workers

**Comment by kozhushman** [comment]
Hello! Prometheus client for [python](https://github.com/prometheus/client_python) (on top of what this package is built) takes this responsibility by itself - check they github page (part about multiprocessing and workers) for more detailed info :)
I personally using my Middleware for app with 10 workers and its all OK :)
