### ISSUE TITLE
requests_created ?

### ISSUE THREAD

**Issue by fiddletwix** [kozhushman/prometheusrock#5]
I poked around the code and Can I get an idea of what the default metric `requests_created` represents?   I keep getting a gauge values which can I seem to interpret properly.

**Comment by kozhushman** [comment]
I don't understand what metric you are talking about. This middleware have 2 default metrics:
Counter: requests_total
Histogram: request_processing_time

Gauge with name `requests_created ` is not one of them.
Can you tell me more about your question?

**Comment by fiddletwix** [comment]
Thanks for the response. so this is my code (filename is test.py):

```
import uvicorn
from fastapi import FastAPI
from prometheusrock import PrometheusMiddleware, metrics_route

app = FastAPI(title="myapp", description="automation tool")

@app.get("/healthcheck")
def healthcheck():
    return {"state": "up"}
app.add_middleware(PrometheusMiddleware, app_name="automator")
app.add_route("/metrics", metrics_route)

if __name__ == "__main__":
    uvicorn.run(
        "test:app",
        host="0.0.0.0",
        port=8001
    )
```

start it up with
```
python ./test.py
```

perform some curls
```
$ curl -s localhost:8001/healthcheck;echo;echo
{"state":"up"}

$ curl -s localhost:8001/metrics|grep requests_created;echo;echo
# HELP requests_created Total HTTP requests
# TYPE requests_created gauge
requests_created{app_name="automator",headers="{'host': 'localhost:8001', 'user-agent': 'curl/7.64.1'}",method="GET",path="/healthcheck",status_code="200"} 1.6192331847982562e+09
```

**Comment by fiddletwix** [comment]
Looking at it closer, it looks like epoch time but I'm not sure what it represents? the last time a request was processed?

**Comment by kozhushman** [comment]
It's a prometheus inner information for representation. For example, if you create a counter - the last number will be counter himself. Don't look deep into those numbers - they are for prometheus use. Time-series, gauge/counter values - every time it will be different and metric-specific
